# Generated by Django 4.2.7 on 2023-12-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='username',
        ),
    ]
