# Generated by Django 4.2.7 on 2023-12-01 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id_card', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.TextField()),
                ('cvv', models.TextField(db_column='CVV')),
                ('grant_date', models.TextField()),
                ('expiration_date', models.TextField()),
                ('card_type', models.TextField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tarjeta.marcas')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'ordering': ['id_card'],
            },
        ),
    ]
