# Generated by Django 4.2.7 on 2023-12-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodecuenta',
            options={'ordering': ['id'], 'verbose_name': 'TipoDeCuenta'},
        ),
    ]
