# Generated by Django 4.2.7 on 2023-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_tipodecuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodecuenta',
            options={'ordering': ['type'], 'verbose_name': 'TipoDeCuenta'},
        ),
    ]
